sudo: required
servcies:
  - docker

before_install:
  - docker build -t evness176/docker-react-dev -f frontend/Dockerfile.dev .

script:
  - docker run -e CI=true evness176/docker-react-dev npm run test